/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitReminderRouteImport } from './routes/visit-reminder'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EducationIndexRouteImport } from './routes/education.index'
import { Route as EducationSlugRouteImport } from './routes/education.$slug'

const VisitReminderRoute = VisitReminderRouteImport.update({
  id: '/visit-reminder',
  path: '/visit-reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationIndexRoute = EducationIndexRouteImport.update({
  id: '/education/',
  path: '/education/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationSlugRoute = EducationSlugRouteImport.update({
  id: '/education/$slug',
  path: '/education/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/edit-profile': typeof EditProfileRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/visit-reminder': typeof VisitReminderRoute
  '/education/$slug': typeof EducationSlugRoute
  '/education/': typeof EducationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/edit-profile': typeof EditProfileRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/visit-reminder': typeof VisitReminderRoute
  '/education/$slug': typeof EducationSlugRoute
  '/education': typeof EducationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/edit-profile': typeof EditProfileRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/visit-reminder': typeof VisitReminderRoute
  '/education/$slug': typeof EducationSlugRoute
  '/education/': typeof EducationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/edit-profile'
    | '/feedback'
    | '/forgot-password'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/register'
    | '/reminders'
    | '/result'
    | '/scan'
    | '/settings'
    | '/visit-reminder'
    | '/education/$slug'
    | '/education/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/edit-profile'
    | '/feedback'
    | '/forgot-password'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/register'
    | '/reminders'
    | '/result'
    | '/scan'
    | '/settings'
    | '/visit-reminder'
    | '/education/$slug'
    | '/education'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/edit-profile'
    | '/feedback'
    | '/forgot-password'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/register'
    | '/reminders'
    | '/result'
    | '/scan'
    | '/settings'
    | '/visit-reminder'
    | '/education/$slug'
    | '/education/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  EditProfileRoute: typeof EditProfileRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  RegisterRoute: typeof RegisterRoute
  RemindersRoute: typeof RemindersRoute
  ResultRoute: typeof ResultRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  VisitReminderRoute: typeof VisitReminderRoute
  EducationSlugRoute: typeof EducationSlugRoute
  EducationIndexRoute: typeof EducationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit-reminder': {
      id: '/visit-reminder'
      path: '/visit-reminder'
      fullPath: '/visit-reminder'
      preLoaderRoute: typeof VisitReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/': {
      id: '/education/'
      path: '/education'
      fullPath: '/education/'
      preLoaderRoute: typeof EducationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/$slug': {
      id: '/education/$slug'
      path: '/education/$slug'
      fullPath: '/education/$slug'
      preLoaderRoute: typeof EducationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  EditProfileRoute: EditProfileRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  RegisterRoute: RegisterRoute,
  RemindersRoute: RemindersRoute,
  ResultRoute: ResultRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  VisitReminderRoute: VisitReminderRoute,
  EducationSlugRoute: EducationSlugRoute,
  EducationIndexRoute: EducationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
